PREFIX sn: <https://sireneld.io/vocab/sirene#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xs: <http://www.w3.org/2001/XMLSchema#>
PREFIX geo-pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>

CONSTRUCT {

    ?entreprise a ?categorie_class ;
    a sn:UniteLegale ;
    a ?categoriejuridiqueUniteLegale_class ;

    sn:siren ?siren ;
    sn:statutDiffusionUniteLegale ?statutDiffusionUniteLegale ;
    sn:unitePurgeeUniteLegale ?unitePurgeeUniteLegale ;
    sn:dateCreationUniteLegale ?dateCreationUniteLegale_date ;
    sn:sigleUniteLegale ?sigleUniteLegale ;
    sn:sexeUniteLegale ?sexeUniteLegale ;
    sn:prenom1UniteLegale ?prenom1UniteLegale ;
    sn:prenom2UniteLegale ?prenom2UniteLegale ;
    sn:prenom3UniteLegale ?prenom3UniteLegale ;
    sn:prenom4UniteLegale ?prenom4UniteLegale ;
    sn:prenomUsuelUniteLegale ?prenomUsuelUniteLegale ;
    sn:pseudonymeUniteLegale ?pseudonymeUniteLegale ;
    sn:identifiantAssociationUniteLegale ?identifiantAssociationUniteLegale ;
    # sn:trancheEffectifsUniteLegale ?trancheEffectifsUniteLegale ;
    sn:anneeEffectifsUniteLegale ?anneeEffectifsUniteLegale_year ;
    sn:dateDernierTraitementUniteLegale ?dateDernierTraitementUniteLegale_date ;
    sn:nombrePeriodesUniteLegale ?nombrePeriodesUniteLegale_integer ;
    # sn:categorieEntreprise ?categorieEntreprise ;
    sn:anneeCategorieEntreprise ?anneeCategorieEntreprise_year ;
    sn:dateDebut ?dateDebut_date ;
    sn:etatAdministratifUniteLegale ?etatAdministratifUniteLegale ;
    sn:nomUniteLegale ?nomUniteLegale ;
    sn:nomUsageUniteLegale ?nomUsageUniteLegale ;
    sn:denominationUniteLegale ?denominationUniteLegale ;
    sn:denominationUsuelle1UniteLegale ?denominationUsuelle1UniteLegale ;
    sn:denominationUsuelle2UniteLegale ?denominationUsuelle2UniteLegale ;
    sn:denominationUsuelle3UniteLegale ?denominationUsuelle3UniteLegale ;
    # sn:categorieJuridiqueUniteLegale ?categorieJuridiqueUniteLegale ;
    # sn:activitePrincipaleUniteLegale ?activitePrincipaleUniteLegale ;
    sn:nomenclatureActivitePrincipaleUniteLegale ?nomenclatureActivitePrincipaleUniteLegale ;
    sn:nicSiegeUniteLegale ?nicSiegeUniteLegale ;
    sn:economieSocialeSolidaireUniteLegale ?economieSocialeSolidaireUniteLegale ;
    sn:caractereEmployeurUniteLegale ?caractereEmployeurUniteLegale ;


    sn:trancheEffectifs ?trancheEffectifsUniteLegale_uri ;
    sn:etatAdministratif ?etatAdministratifUniteLegale_uri ;
    sn:activitePrincipale ?activitePrincipaleUniteLegale_uri ;
    sn:siege ?nicSiegeUniteLegale_uri .
}

WHERE {
    bind(uri(concat("https://sireneld.io/vocab/sirene#",?categorieEntreprise)) as ?categorie_class)
    bind(uri(concat("https://sireneld.io/vocab/sirecj#",?categorieJuridiqueUniteLegale)) as ?categorieJuridiqueUniteLegale_class)
    bind(uri(concat("https://sireneld.io/siren/",?siren)) as ?entreprise)
    bind(uri(concat("https://sireneld.io/tef/",?trancheEffectifsUniteLegale)) as ?trancheEffectifsUniteLegale_uri)
    bind(uri(concat("https://sireneld.io/etatAdministratif/",?etatAdministratifUniteLegale)) as ?etatAdministratifUniteLegale_uri)
    bind(if(?nomenclatureActivitePrincipaleUniteLegale = "NAFRev2", uri(concat("http://id.insee.fr/codes/nafr2/sousClasse/", ?activitePrincipaleUniteLegale)),?null) as ?activitePrincipaleUniteLegale_uri)
    bind(uri(concat("https://sireneld.io/siret/",?siren,?nicSiegeUniteLegale)) as ?nicSiegeUniteLegale_uri)

    bind(xs:date(?dateCreationUniteLegale) as ?dateCreationUniteLegale_date)
    bind(xs:gYear(?anneeEffectifsUniteLegale) as ?anneeEffectifsUniteLegale_year)
    bind(xs:date(?dateDernierTraitementUniteLegale) as ?dateDernierTraitementUniteLegale_date)
    bind(xs:int(?nombrePeriodesUniteLegale) as ?nombrePeriodesUniteLegale_integer)
    bind(xs:gYear(?anneeCategorieEntreprise) as ?anneeCategorieEntreprise_year)
    bind(xs:date(?dateDebut) as ?dateDebut_date)
}
